version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10

  build:
    commands:
      - npm i react-scripts
      - npm run build
    
artifacts:
  files:
    - 'build/**/*'
  base-directory: '/'
  discard-paths: no